#pragma once
// Generated by the main.cpp module split: the code below is a verbatim
// slice of the original single-translation-unit firmware/src/main.cpp.

#include "yat_common.h"

// Defined in the content-portal section near the bottom of this file. Three
// things reach it — the green-button gesture, a first-time provisioning that
// just succeeded, and `YAT PORTAL` — and the last of those arrives from inside
// a console window, which is why it is declared this far up.
enum class PortalEntry { Gesture, Provisioned, Console };
[[noreturn]] void runContentPortal(PortalEntry entry);

[[noreturn]] void refuseSetupLowBattery(float volts, bool userInitiated);
