#pragma once
// Generated by the main.cpp module split: the code below is a verbatim
// slice of the original single-translation-unit firmware/src/main.cpp.

#include <stddef.h>
#include <stdint.h>

// ---------------- the error ring (what went wrong, in the household's terms) ----------------
//
// A device that fails quietly is the worst thing this product can be: the panel
// holds its last image with the power off, so "the screen stopped changing" is
// the only symptom of every fault there is, and nothing on the device has ever
// been able to say which one it was. The serial log knows, but the log is gone
// the moment the USB cable is — this firmware sleeps between cycles, and the
// household has no terminal.
//
// So the last few failures live here instead: eight slots in .bss, mirrored to
// NVS ("yat"/"err_ring") so they survive deep sleep, read back out by
// GET /api/status (the setup portal's 裝置最近嘅問題 card) and by YAT ERRORS.
// What goes in is only what a household could act on or would recognise —
// seven codes, listed at ERR_SRC_FETCH below — never a stack trace, a URL or an
// HTTP body, and never any part of a key: nothing on this path ever sees a
// secret, and the two code paths that hold one (voiceTranscribe, the LLM
// router) record the token alone.
//
// Three properties make it safe to call from inside a failure path, which is
// the only place it is ever called from:
//
//   - It cannot allocate. The ring is a fixed POD array; the only heap the call
//     touches is whatever NVS uses internally, and a full or unmountable NVS
//     makes putBytes fail, not throw.
//   - It cannot grow. Eight entries, a 12-byte code and a 32-byte context
//     string each, both clipped on a UTF-8 boundary so a long page id can never
//     leave the /api/status body invalid.
//   - It cannot drown itself out. A repeat of the newest entry (same code, same
//     context) refreshes its timestamp instead of pushing a ninth: a router
//     that has been down for three days would otherwise fill all eight slots
//     with one message and bury the STT failure the household actually wants
//     explained. The row therefore reports the most recent occurrence of a
//     fault, not its first.
static constexpr size_t ERR_RING_N = 8;
static constexpr size_t ERR_CODE_BYTES = 12;
static constexpr size_t ERR_PAGE_BYTES = 32;
static constexpr uint8_t ERR_RING_VERSION = 1;

// The complete token set, and a sealed cross-lane contract exactly like
// portalSendError's `detail` words: the setup portal carries one bilingual
// sentence per token and generic copy for anything else, so an eighth token
// cannot be added here without telling the site lane first.
//
//   src_fetch  a page's data source did not answer      (context: page id)
//   stt_http   the speech-to-text request failed        (context: none)
//   llm_http   the voice router's request failed        (context: none)
//   render     the page loaded but would not draw       (context: page id)
//   fs_write   a write to the device's storage failed   (context: file path)
//   wifi_lost  the home network was not there this cycle (context: none)
//   ota        a firmware update the household asked for did not install
//              (context: the OTA_ERR_* token saying which way it failed —
//              yat_ota.h, and the portal has a sentence per token)
static const char* const ERR_SRC_FETCH = "src_fetch";
static const char* const ERR_STT_HTTP = "stt_http";
static const char* const ERR_LLM_HTTP = "llm_http";
static const char* const ERR_RENDER = "render";
static const char* const ERR_FS_WRITE = "fs_write";
static const char* const ERR_WIFI_LOST = "wifi_lost";
static const char* const ERR_OTA = "ota";

struct ErrEntry {
  // Unix epoch, or 0 when the clock had not been synced yet — a plain 0 is
  // honest ("this happened, we don't know when") in a way that a 1970 date
  // dressed up as a real one is not. The portal shows those rows undated.
  uint32_t t;
  char code[ERR_CODE_BYTES];
  char page[ERR_PAGE_BYTES];
};

// Persisted whole, in one putBytes, so the ring can never be half-updated by a
// power cut mid-write: either the previous eight or the new eight.
struct ErrRing {
  uint8_t version;
  uint8_t count;  // slots filled, <= ERR_RING_N
  uint8_t next;   // where the next entry goes
  uint8_t reserved;
  ErrEntry e[ERR_RING_N];
};

extern uint32_t g_errTotal;

void errCopyField(char* dst, size_t cap, const char* src);

// `httpStatus` is the provider's own status code where the caller has one, and
// 0 everywhere else. It is not stored and never reaches the ring — it exists
// for exactly one decision, made in recordError and nowhere else: 401/403 is a
// key the provider REJECTED, which is a person's problem and gets a condition
// below, where a timeout or a 502 is the network's problem and gets a row and
// nothing more. Same fault to the household either way until you ask what
// would fix it.
void recordError(const char* code, const char* context, int httpStatus = 0);
const ErrEntry* errAt(size_t i);
void restoreErrorRingFromNvs();

// ---------------- conditions (what is still TRUE) ----------------
//
// The ring above answers "what went wrong recently". It cannot answer "is the
// device still broken", and that is the only question the panel's §11.4a
// Action banner may be drawn from: a row saying the voice router failed at
// 09:14 is history, and putting history on a household's wall in a banner that
// says "do something" is how a display teaches people to ignore it.
//
// So conditions are separate state: one bit each, set when a fault is
// diagnosed, cleared when the matching success proves it over, persisted in
// NVS ("err_cond") because every one of them outlives a deep sleep by
// definition. Only three, and each one is genuinely a person's to fix — none
// of them will clear on its own no matter how long the device waits, which is
// exactly what separates them from a failing source (that one heals, and gets
// the quieter Degraded strip instead).
static constexpr uint32_t COND_VOICE_KEY = 1u << 0;  // a provider rejected the key (401/403)
static constexpr uint32_t COND_STORAGE = 1u << 1;    // writes to LittleFS are failing
static constexpr uint32_t COND_CONFIG = 1u << 2;     // the device cannot read its own settings
static constexpr size_t COND_N = 3;

// Idempotent. Re-asserting a condition already up refreshes its clock (which
// is what the expiry below reads) but writes to flash at most hourly, so a
// source failing every wake cannot wear the part out.
void conditionSet(uint32_t bit);

// Also idempotent, and free when the bit was not set — which is the common
// case, since the clear lives on the success path and most devices never fail.
void conditionClear(uint32_t bit);

// The bits still in force, with anything unrefreshed for a week dropped.
//
// The expiry is not a safety net for a missed clear; it is the honest answer
// to "we have been telling this household to fix their voice key for seven
// days and they have not". A banner nobody acts on is furniture, and the
// condition re-asserts the instant the thing is tried again — so the panel
// stops nagging without the device ever forgetting. A condition stamped before
// the clock was synced (epoch 0) never expires: it cannot be aged honestly.
uint32_t conditionsActive();

extern bool g_fetchErrRecord;
extern char g_fetchErrPage[ERR_PAGE_BYTES];

extern bool g_fetchErrRecord;
extern char g_fetchErrPage[ERR_PAGE_BYTES];
