#pragma once
// Generated by the main.cpp module split: the code below is a verbatim
// slice of the original single-translation-unit firmware/src/main.cpp.

#include <Arduino.h>
#include <time.h>

#include <yat/canvas.h>

// ---------------- which model this build is for ----------------
//
// platformio.ini defines exactly one YAT_MODEL_*, alongside the Seeed_GFX
// BOARD_SCREEN_COMBO that picks the matching panel driver. Everything else
// this firmware needs to know about the model is derived here, once, so a
// third model is a block in this section rather than a new #ifdef in every
// file that cares:
//
//   YAT_MODEL_NAME   the wire name — OTA asset filename, /api/status "model",
//                    serial STATUS "model". Must match .github/workflows/
//                    release.yml's matrix entry, which is what publishes
//                    firmware-<model>.bin.
//   kPanelProfile    the engine's DeviceProfile (canvas.h) every render()
//                    call site passes, so role- and literal-named inks are
//                    clamped to what this panel can actually show.
//   PANEL_REFRESH_S  how long a full refresh takes, for the one place we make
//                    a claim about it to somebody waiting (see below).
//
// The two models share the carrier board — identical pins, identical 800x480
// geometry — and differ only in the panel: E1002 is Spectra 6 (ED2208, 4bpp,
// six inks), E1001 is mono (UC8179, 1bpp, black/white).
#if defined(YAT_MODEL_E1001)
#define YAT_MODEL_NAME "e1001"
inline constexpr const yat::DeviceProfile& kPanelProfile = yat::kProfileE1001;
#elif defined(YAT_MODEL_E1002)
#define YAT_MODEL_NAME "e1002"
inline constexpr const yat::DeviceProfile& kPanelProfile = yat::kProfileE1002;
#else
#error "No YAT_MODEL_* defined — build through platformio.ini's e1001/e1002 env"
#endif

static constexpr const char* MODEL_NAME = YAT_MODEL_NAME;

// The macro and the profile are two spellings of the same fact, and the OTA
// asset name is built from the macro while /api/status reports the profile's
// own field — so make them impossible to disagree.
constexpr bool modelNamesAgree(const char* a, const char* b) {
  while (*a && *a == *b) {
    a++;
    b++;
  }
  return *a == *b;
}
static_assert(modelNamesAgree(YAT_MODEL_NAME, kPanelProfile.name),
              "YAT_MODEL_NAME and the engine DeviceProfile disagree about this model's name");

// An UPPER BOUND on how long the panel blocks for a full refresh, in seconds —
// the number the setup portal hands a phone so its progress copy can count
// down (see yat_portal.cpp's apply reply). A ceiling rather than a typical
// value on purpose: every consumer of it is somebody being asked to wait, and
// the only way to be wrong that breaks anything is to be under.
//
// E1002: ~30 s measured on the hardware, so 35 with a margin.
//
// E1001: NOT YET MEASURED. Mono panels are usually much faster than an E6,
// but the UC8179's real full-refresh time on this board is a hardware fact
// nobody here has observed, and guessing LOW is the one direction that
// breaks something — the portal would tell the household setup finished while
// the panel is still mid-refresh. So it starts at the E1002's number, which is
// only ever too generous, and the honest fix is one measurement.
// TODO(hardware): time epaper.update() on an E1001 and set this to that value
// plus a small margin. The [epd] log line in yat_sched.cpp prints the measured
// milliseconds of every refresh, so the number is one flash and one wake away.
#if defined(YAT_MODEL_E1001)
static constexpr uint32_t PANEL_REFRESH_S = 35;  // placeholder: E1002's number, deliberately
#else
static constexpr uint32_t PANEL_REFRESH_S = 35;  // measured (~30 s) + margin
#endif

// ---------------- pins (reTerminal E1001/E1002 carrier board) ----------------
static constexpr int PIN_LED = 6;  // inverted: LOW = on
static constexpr int PIN_KEY0 = 3;  // active-low, RTC-capable -> ext1 wake (tap: tap-to-talk voice; hold 5s: provisioning)
static constexpr int PIN_KEY1 = 4;  // active-low, RTC-capable -> ext1 wake (page forward)
static constexpr int PIN_KEY2 = 5;  // active-low, RTC-capable -> ext1 wake (page backward)
static constexpr int PIN_I2C_SDA = 19;
static constexpr int PIN_I2C_SCL = 20;
static constexpr int PIN_BAT_ADC = 1;
static constexpr int PIN_BAT_EN = 21;
static constexpr int PIN_DBG_RX = 44;
static constexpr int PIN_DBG_TX = 43;
// Voice hardware (PRD §4.4, all confirmed on this board by
// the e1002-test prototype (private) — selftest's beep/bootMelody for the buzzer,
// voicedemo's recorder for the PDM mic).
static constexpr int PIN_BUZZER = 45;    // passive buzzer, driven by tone() (LEDC under the hood)
static constexpr int PIN_MIC_CLK = 42;   // PDM clock
static constexpr int PIN_MIC_DATA = 41;  // PDM data
static constexpr int PIN_MIC_EN = 38;    // HIGH = mic powered; held HIGH only while recording

static constexpr uint8_t ADDR_SHT4X = 0x44;

static constexpr int SCREEN_W = 800, SCREEN_H = 480;

// Base version bumps by hand at feature milestones; the build stamps the git
// revision on automatically (version_stamp.py) so every dev flash names its
// exact commit — "0.4.0-dev+34a4b68" — in STATUS, /api/status, the panel
// footer and the boot banner. Release builds drop the suffix by tagging.
#ifndef YAT_BUILD_REV
#define YAT_BUILD_REV ""
#endif
static constexpr const char* FW_VERSION = "0.5.0-beta" YAT_BUILD_REV;

// Fallback cadence when a pack has no usable schedule.default.every_min, or
// the clock never synced so window/quiet-hours math can't run (§ scheduler
// below). The normal path reads the real value from the loaded pack.
static constexpr uint32_t SCHEDULE_MIN = 60;

// Failure backoff ladder (deepSleepError). A failure that clears on the next
// wake is the common case, so the first retry stays at 5 minutes; a source
// that is permanently broken must not keep that cadence, because 288 wakes a
// day — all night, forever — flattens the battery without anything on the
// panel changing to say why. Consecutive failed cycles (NVS "err_n") escalate
// 5 -> 15 -> 60 min, and the retry itself honors quiet hours from there on.
static constexpr uint32_t RETRY_MIN = 5;  // WiFi / fetch / load failure backoff
static constexpr uint32_t RETRY_MID_MIN = 15;
static constexpr uint32_t RETRY_MAX_MIN = 60;

// Ceiling on any sleep while a warning takeover is up (PRD §4.2/§5.1), applied
// both to the schedule (clampForTakeover) and to the failure ladder above: a
// typhoon signal that a failing fetch pushes an hour out of date is the one
// case where reaction time beats battery.
static constexpr uint64_t TAKEOVER_MAX_SLEEP_S = 15 * 60;

// G9: the provisioning portal must not be a one-way door. Bound how long it
// stays up (WiFiManager's own default is unbounded, at full AP-mode power),
// and when nobody completes it in that window, go back to sleep and let the
// saved credentials (untouched in NVS) try again next wake — a router that
// comes back while nobody's home should not require a manual rescue.
// The retry itself escalates 30 -> 60 -> 180 min across an unattended streak,
// and honors quiet hours from there on, exactly as the failure ladder above
// does — see the streak counter above runProvisioningMode().
static constexpr uint32_t PORTAL_TIMEOUT_S = 600;        // 10 min
static constexpr uint32_t PORTAL_RETRY_SLEEP_MIN = 30;    // first retry of a streak

// Content portal — the second, content-picking half of the one setup gesture
// (green button held 5 s). Distinct from the WiFi provisioning portal above:
// that one collects credentials through WiFiManager, this one is our own HTTP
// server handing a phone the pack library. See the "content portal" section
// near the bottom of this file.
//   - MIN_VOLTS: setup mode runs an AP, a WiFi client and up to two 30 s panel
//     refreshes back to back. That is the heaviest thing this firmware ever
//     does, and it is user-initiated, so it can be declined: below this the
//     gesture draws a "plug in first" card instead of opening the portal. Well
//     above LOW_BATTERY_PCT's own cutoff (~3.37 V), which is about survival
//     rather than about refusing one expensive optional mode.
//   - IDLE_MS: nobody should be able to leave the device beaconing overnight
//     by walking away mid-setup. Any /api/* hit resets it; screen B says so.
//   - MAX_BODY: same 64 KB pack-file cap PACK-SPEC §12.1 puts on the serial
//     PUT path, applied to request bodies before a byte is buffered.
//   - MAX_SECRET: no STT provider issues a credential anywhere near this long,
//     so a longer one is a pasted mistake, not a key — and NVS should not be
//     asked to store it.
static constexpr float CONTENT_PORTAL_MIN_VOLTS = 3.50f;
static constexpr uint32_t CONTENT_PORTAL_IDLE_MS = 600000;  // 10 min
static constexpr size_t CONTENT_PORTAL_MAX_BODY = 65536;
static constexpr size_t CONTENT_PORTAL_MAX_SECRET = 256;

static constexpr uint32_t WIFI_TIMEOUT_MS = 15000;
static constexpr uint32_t SNTP_TIMEOUT_MS = 5000;

// 2024-01-01. Anything below this is the un-synced 1970 epoch, which is the
// only thing distinguishing "the clock has never been set on this boot" from
// a real time — see restoreClockFromNvs()/syncTime().
static constexpr time_t CLOCK_SANE_EPOCH = 1704067200;

// G25/G26 (docs/UX-FLOWS.md): no fuel-gauge chip on this board, so
// batteryVolts() is mapped to a percent with a straight line between empty
// and full for a single-cell Li-ion/LiPo — honest and crude (not gas-gauge
// accurate near either end), but enough for a footer glyph and a cutoff.
// Below LOW_BATTERY_PCT the whole cycle is skipped — no WiFi, no fetch, no
// pack load — in favor of a firmware-owned low-battery card and a long
// low-power sleep; see its call site in setup().
static constexpr float BATTERY_EMPTY_V = 3.3f;
static constexpr float BATTERY_FULL_V = 4.2f;
static constexpr int LOW_BATTERY_PCT = 8;
static constexpr uint32_t LOW_BATTERY_SLEEP_MIN = 360;  // 6 h

// Crash-loop breaker (audit #18). A deterministic fault — a pack the renderer
// mishandles, an image that trips the decoder — costs far more than one bad
// cycle: the panic reboots, the cycle starts again from the top, and it faults
// at the same place forever. Nothing on the panel says why, the console window
// never opens long enough to be caught, and a device that should have lasted
// weeks is flat inside a day.
//
// So consecutive crash resets are counted (NVS "panic_n"), and the third one
// stops the cycle before the filesystem is even mounted: a calm card, no pack
// render at all, and a long sleep. The count clears on any cycle that ends with
// content on the panel, and on the green button — the card tells the household
// to press it, so it has to be the way out.
//
// Only genuine firmware faults count. A brownout is a power problem, which this
// board has and this file is full of workarounds for; telling a household with
// a tired battery that its device is broken would be both wrong and unhelpful.
// A deliberate ESP.restart() (finishProvisioning) is not a fault either.
static constexpr uint32_t PANIC_SAFE_MODE_N = 3;
static constexpr uint32_t SAFE_MODE_SLEEP_MIN = 60;

// How long the help card is left up when nobody dismisses it. Pressing any
// button wakes the device immediately and takes the card away, which is the
// path the card's own last line describes and the one almost everyone will
// use; this is only the fallback for a household that read it and wandered
// off. Short enough that walking away never costs you your pages for long,
// long enough that it is not a second refresh charged to someone who is still
// reading.
static constexpr uint32_t HELP_CARD_SLEEP_MIN = 10;

// Serial file-protocol console window, opened before every sleep and on any
// mid-cycle serial activity (ARCHITECTURE §4 "serial protocol").
//   - CONSOLE_WINDOW_MS: how long to wait for a FIRST byte before giving up and
//     sleeping (kept short so a normal, unattended cycle isn't held awake).
//   - CONSOLE_SESSION_IDLE_MS: once someone is actually talking to us, tolerate
//     much longer human gaps between commands. Content setup on the site is a
//     multi-step, click-by-click session; at 10 s the device would sleep in the
//     pause between clicks — and since Serial here is the ESP32-S3 native USB
//     (ARDUINO_USB_CDC_ON_BOOT), sleeping DROPS the USB link mid-transfer, so
//     the next PUT/GET arrives truncated and reads as "invalid json". Staying
//     awake only costs battery while a session is genuinely in progress (rare).
static constexpr uint32_t CONSOLE_WINDOW_MS = 10000;
static constexpr uint32_t CONSOLE_SESSION_IDLE_MS = 180000;  // 3 min between commands

// Hong Kong: POSIX TZ sign is inverted, so "HKT-8" means UTC+8. No DST.
static constexpr const char* TZ_HK = "HKT-8";

// Debug log goes to Serial ONLY — the ESP32-S3 native USB-Serial-JTAG. The YAT
// console + Improv now live on Serial1 (the CH340 UART, PIN_DBG 43/44), because
// opening the USB-Serial-JTAG from a host resets the chip (that's the hardware
// download-reset esptool uses) — which reset the board every time the setup
// website connected. Keeping LOGF off Serial1 also means the console stream
// the website reads/writes is never polluted by debug lines mid-transfer.
// YAT_LOG_MIRROR_UART additionally copies every LOGF line onto Serial1 (the
// CH340). Debug-capture builds only: on this hardware path the native USB
// often never enumerates on a hub, so the JTAG log is unreachable and the
// CH340 is the only line out. It pollutes the console protocol the website
// speaks — never ship it on.
#ifdef YAT_LOG_MIRROR_UART
#define LOGF(...)                  \
  do {                             \
    Serial.printf(__VA_ARGS__);    \
    Serial1.printf(__VA_ARGS__);   \
  } while (0)
#else
#define LOGF(...)                  \
  do {                             \
    Serial.printf(__VA_ARGS__);    \
  } while (0)
#endif

// Defined in main.cpp, next to the SET_LOOP_TASK_STACK_SIZE it reports against.
void logStackHeadroom(const char* where);
