#pragma once
// Generated by the main.cpp module split: the code below is a verbatim
// slice of the original single-translation-unit firmware/src/main.cpp.

#include <stdint.h>

#include <Arduino.h>
#include <ImprovWiFiLibrary.h>

#include "yat_common.h"

extern ImprovWiFi g_improv;

extern volatile bool g_portalRequested;
extern bool g_inContentPortal;

bool sttKeyPresent();
void pumpConsoleByte();
void consoleWindow(uint32_t windowMs);
void maybeRunRequestedPortal();
void maybeEnterConsole(const char* when);

bool improvConnectCb(const char* ssid, const char* pass);
void improvErrorCb(ImprovTypes::Error err);
void improvConnectedCb(const char* ssid, const char*);

