#pragma once
// Generated by the main.cpp module split: the code below is a verbatim
// slice of the original single-translation-unit firmware/src/main.cpp.
// Declaration mirror for the cross-cutting cycle state main.cpp defines. Every
// one of these is documented at its definition, at the top of main.cpp.

#include <stdint.h>

#include <string>

#include <WiFiManager.h>
#include <freertos/FreeRTOS.h>
#include <freertos/task.h>

extern WiFiManager g_wm;

extern bool g_panelReady;
extern bool g_buttonWake;
extern bool g_pageForward;
extern bool g_pageBack;
extern bool g_helpRequested;
extern bool g_serialForceRender;
extern bool g_coldBootWake;
extern bool g_loopAdvanced;
extern bool g_fsReady;
extern bool g_fsFormatted;
extern uint32_t g_lastHash;
extern uint64_t g_plannedSleepSeconds;
extern uint32_t g_panicStreak;
extern bool g_renderOk;
extern std::string g_renderedPage;
extern bool g_takeoverActive;
extern std::string g_takeoverSignal;

extern char g_apSsid[24];
extern char g_apPass[9];
extern char g_qrWifiPayload[80];

extern volatile bool g_portalSuccess;
extern volatile bool g_improvSaved;
extern TaskHandle_t g_portalTaskHandle;

