#pragma once
// Generated by the main.cpp module split: the code below is a verbatim
// slice of the original single-translation-unit firmware/src/main.cpp.

#include <string>
#include <vector>

#include <ArduinoJson.h>
#include <LittleFS.h>
#include <yat/engine.h>

#include "yat_common.h"

extern const char* const DEFAULT_CONFIG_JSON;

bool littlefsReadFile(const char* path, std::string& out);
bool littlefsWriteFile(const char* path, const void* data, size_t len);
void ensureDefaults();

// §11.3/§5.1 yat::StateStore backed by one file per key under /state/ on the
// already-mounted LittleFS. Keys are "<packid>.<sourceid>"; PACK-SPEC's
// packid/sourceid schemas (§3/§5) already restrict those to [a-z0-9._-], so
// they're filename-safe as-is, but sanitize() still defensively substitutes
// anything outside that set — this store has no other way to reject a
// malformed key, and a stray '/' must never be allowed to escape /state/.
struct LittleFsStateStore : yat::StateStore {
  static std::string sanitize(const char* key) {
    std::string s;
    for (const char* p = key; *p; p++) {
      char c = *p;
      bool ok = (c >= 'a' && c <= 'z') || (c >= '0' && c <= '9') || c == '.' || c == '_' || c == '-';
      s += ok ? c : '_';
    }
    return s.empty() ? std::string("_") : s;
  }
  static std::string pathFor(const char* key) { return "/state/" + sanitize(key); }

  bool get(const char* key, std::string& out) override {
    return littlefsReadFile(pathFor(key).c_str(), out);
  }
  bool put(const char* key, const std::string& val) override {
    if (!LittleFS.exists("/state")) LittleFS.mkdir("/state");
    return littlefsWriteFile(pathFor(key).c_str(), val.data(), val.size());
  }
};

// Config v2 (Task A, ARCHITECTURE §4 extended): one page became 1..16.
// aliases exists in the schema now so a hand-written/migrated config.json
// round-trips through GET/PUT without losing it, but nothing matches against
// it yet — voice arrives in Task B.
struct ConfigPage {
  std::string id;
  std::string pack;
  std::string paramsJson;  // serialized params object; empty => none
  std::vector<std::string> aliases;
  int everyMin = 0;  // per-page cadence override, minutes; 0 => follow the pack's schedule
};

// config.json pages[].every_min — the user's answer to "how often should THIS
// page update", overriding the pack author's schedule (see computeSleepPlan).
// 5 min is the same platform cadence floor PACK-SPEC §12.1 puts on the pack's
// own every_min; 1440 is a day, past which this stops being a cadence.
static constexpr int PAGE_EVERY_MIN_MIN = 5;
static constexpr int PAGE_EVERY_MIN_MAX = 1440;

// config.json "voice": {"seconds": N} — how long a KEY0 tap records (PRD §4.4).
// Clamped: below 2 s nobody can finish saying "巴士幾時到", and above 8 s the
// PSRAM buffer and the upload both grow for no accuracy gain (16 kHz mono
// 16-bit = 32 KB/s, so 8 s is already a 256 KB body).
static constexpr int VOICE_SECONDS_DEFAULT = 4;
static constexpr int VOICE_SECONDS_MIN = 2;
static constexpr int VOICE_SECONDS_MAX = 8;

// config.json "loop_min" — auto-rotate: the device walks to the next page by
// itself every N minutes, so a household with four pages sees all four without
// touching a button. Absent or 0 is off, and the only other values are 30, 60
// and 180.
//
// That ladder is the product decision, not a parser convenience. Every advance
// is a full 30 s panel refresh whether or not a single number on the page
// changed, so it is paid twice: in battery, and in the panel's finite rated
// refresh count. A 5-minute rotation would spend both on pages nobody asked to
// see. So a hand-edited value off the ladder is snapped to a rung rather than
// honored — and upward within the ladder, because the floor is the whole point.
static constexpr int kLoopMinChoices[] = {30, 60, 180};

// config.json "llm_model" — which chat model the voice router asks for, on
// whichever of the two services the stored key selects. Absent is the normal
// case and leaves each provider on its own default (the `model` column of
// kLlmProviders), chosen so that which service a household ended up on is not a
// decision about quality they had to make.
//
// Deliberately config-only, with no control anywhere in the portal. Picking a
// model is a question about price and capability that the audience this product
// is built for has no way to answer and no reason to be asked; it exists for
// the household that has someone willing to edit a file, and for us when we
// want to try a different router on real hardware without a firmware build.
static constexpr size_t kLlmModelMax = 64;

struct DeviceConfig {
  std::vector<ConfigPage> pages;
  std::string quietStart, quietEnd;    // "HH:MM"; both empty => quiet hours disabled
  int voiceSeconds = VOICE_SECONDS_DEFAULT;
  bool beep = true;  // config.json "beep"; absent => true. See the beep vocabulary block.
  int loopMin = 0;   // config.json "loop_min"; 0 => no auto-rotate. See kLoopMinChoices.
  std::string llmModel;  // config.json "llm_model"; empty => the active provider's default.
};

extern std::string g_quietStart, g_quietEnd;
extern bool g_beepEnabled;
extern int g_loopMin;
extern std::string g_llmModel;

void restoreBeepPrefFromNvs();
bool parsePagesFromV2(JsonVariantConst pagesNode, DeviceConfig& cfg);
DeviceConfig loadConfig(bool fsReady);

// ---------------- the one pack the device writes back (PRD §4.4 intents) ----------------
//
// Every other pack's params are read-only to the firmware: the household sets
// them in the portal and the device renders them. The household todo list is
// the exception — voice can add an item, mark one done, or clear the done ones
// — so these three bounds are the pack's own schema restated on the writing
// side, because the firmware is what has to refuse to exceed them.
static constexpr const char* TODO_PACK_ID = "todo";
// 20, not a number this side picked: PACK-SPEC §3.2/§12.1 hard-caps any array
// param at 20 entries, so that is what the todo pack's schema declares and
// what the portal will accept. Voice must refuse at the same number the portal
// does, or the household gets a 21st item by voice that no later save from the
// settings page will keep.
static constexpr size_t TODO_MAX_ITEMS = 20;
// Codepoints, not bytes: the schema counts characters, and 48 Chinese
// characters are 144 UTF-8 bytes. A full list is therefore ~3.5 KB of params,
// against a 64 KB config — see savePageParams()'s own ceiling check.
static constexpr size_t TODO_MAX_TEXT_CP = 48;

// Replaces pages[<pageIdx>].params in /config.json with `paramsJson`, leaving
// every other byte of the file — quiet hours, the beep switch, the other pages,
// anything a hand-edit added that this firmware has never heard of — exactly as
// it found it, and mirrors the new value into g_pages[pageIdx].paramsJson so the
// refresh THIS cycle draws it. Same write machinery the portal's apply path
// uses (littlefsWriteFile: temp file, size check, atomic rename), so an
// interruption leaves the old params or the new ones and never a half list.
bool savePageParams(int pageIdx, const std::string& paramsJson);

int loadClampedPageIdx(size_t numPages);
extern time_t g_loopOriginEpoch;
void saveLoopOrigin(time_t when);
time_t loadLoopOrigin();
void savePageIdx(int idx);

extern std::vector<ConfigPage> g_pages;
extern int g_activePageIdx;
extern int g_voiceSeconds;
