#pragma once
// Generated by the main.cpp module split: the code below is a verbatim
// slice of the original single-translation-unit firmware/src/main.cpp.

#include <stdint.h>

#include "yat_net.h"
#include "yat_common.h"

extern bool g_keySetupMode;
extern bool g_packCommitted;
extern bool g_keyForceRender;
extern bool g_keyRerenderPending;

void armButtonInterrupts();
void disarmButtonInterrupts();

extern WifiCreds g_keyCreds;

bool takeHelpRequest();

// Acts on whatever has been latched since the last checkpoint. Defined far
// below, next to the voice capture and the beep vocabulary it needs; declared
// here because the console window, the sleep path and both portals all call it.
// `where` names the checkpoint, for the log only.
// `lastChance` marks the final checkpoint before deep sleep, where a lone
// arrow latch can no longer be left pending for a later one — see the
// definition.
void processKeyLatches(const char* where, bool lastChance = false);
