#pragma once
// Generated by the main.cpp module split: the code below is a verbatim
// slice of the original single-translation-unit firmware/src/main.cpp.

#include <stdint.h>

#include <string>

#include "yat_sched.h"
#include "yat_common.h"

struct WifiCreds {
  std::string ssid, pass;
  bool valid = false;
};

struct WarnsumResult {
  bool ok = false;      // fetch + parse succeeded
  bool active = false;  // only meaningful when ok
  std::string signal;   // e.g. "TC8NE", "WRAINB"; "" when inactive
};

WifiCreds loadWifiCreds();
void saveWifiCreds(const char* ssid, const char* pass);
uint32_t wifiFailCount();
void wifiRecordFailure();
void wifiRecordSuccess();
void maybeSeedWifiFromSecrets();

bool wifiConnect(const char* ssid, const char* pass);
void restoreClockFromNvs();
bool syncTime();
bool httpsFetch(const std::string& sourceId, const std::string& url, std::string& bodyOut,
                std::string& errOut);

// The FetchFn a pack's own declared sources are wired to (main.cpp, yat_portal.cpp) —
// httpsFetch() plus the PACK-SPEC §12.3 rule 2 private/loopback-range guard
// (E_FETCH_BLOCKED). Firmware's own fetches (fetchWarnsumDecision, OTA, the
// portal server itself) do not go through this and call httpsFetch()
// directly — see the comment above fetchPackSource()'s definition.
bool fetchPackSource(const std::string& sourceId, const std::string& url, std::string& bodyOut,
                      std::string& errOut);

WarnsumResult fetchWarnsumDecision();
void clampForTakeover(SleepPlan& plan);
