#pragma once
// Generated by the main.cpp module split: the code below is a verbatim
// slice of the original single-translation-unit firmware/src/main.cpp.

#include <stdint.h>

void beep(uint16_t freq, uint16_t ms);

void beepRecordStart();
void beepRecordStop();
void beepMatch();
void beepError();
void beepNoMatch();
void beepHeldForLater();
void beepNoKey();
void beepEnterSetup();
void beepHoldConfirmed();
void beepPageStep();
void beepNewError();
void beepUpdateDone();

