#pragma once
// Generated by the main.cpp module split: the code below is a verbatim
// slice of the original single-translation-unit firmware/src/main.cpp.

#include <stdint.h>

#include <string>

#include "yat_common.h"

enum class KeyVerdict : uint8_t { Valid, Rejected, Unreachable, Inconclusive };

const char* llmProvider();

// What one router call came back with, already validated against the things
// that actually exist on this device: `pageIdx` is a real index into g_pages,
// `itemIdx` is a real position in the todo list, and `text` is only ever set
// for an add. Anything the model said that did not survive that check arrives
// here as None, which is the same answer a device with no key gives.
struct LlmVoiceAnswer {
  enum Kind : uint8_t { None, Page, TodoAdd, TodoDone, TodoClear };
  Kind kind = None;
  int pageIdx = -1;    // Page
  std::string text;    // TodoAdd
  int itemIdx = -1;    // TodoDone — absolute position in the stored list
};

// `todoInstalled` false builds byte-for-byte the page-only request this has
// always sent, and can only ever answer Page or None. True adds the open todo
// items to the prompt and the four extra answer shapes.
LlmVoiceAnswer voiceRouteByLlm(const std::string& transcript, bool todoInstalled);
KeyVerdict verifySecretKey(bool stt, const char* value);
