#pragma once
// Generated by the main.cpp module split: the code below is a verbatim
// slice of the original single-translation-unit firmware/src/main.cpp.

#include <stdint.h>

#include <string>
#include <vector>

#include <ArduinoJson.h>
#include <yat/engine.h>

#include "yat_hw.h"
#include "yat_common.h"

// Small QR/text renderer for the firmware-owned screens only: straight onto the
// EPaperCanvas, no pack involved. engine/src/render.cpp has file-private
// equivalents (drawGlyph/drawTextRun/utf8Next/glyphAdvance, and the "qr"
// widget's qrcodegen call) that aren't exposed via yat/engine.h, so this is the
// same ~40 lines again rather than a header change there — but the *glyphs and
// metrics* are no longer duplicated: both go through yat::fontGlyph, so these
// screens use the identical faces and proportional advances the engine does.
//
// `px` is a face size (16/24/32/48); `y` is the top of the line box, as before.
namespace prov {

size_t utf8Next(const std::string& s, size_t i, uint16_t& code);
void drawGlyph(yat::Canvas& cv, const yat::GlyphInfo& g, int penX, int baselineY, yat::Ink ink);
int drawText(yat::Canvas& cv, yat::FontProvider& font, int x, int y, const std::string& s, int px,
             yat::Ink ink, bool bold = false);
int textWidth(const std::string& s, int px, bool bold = false);
void drawQR(yat::Canvas& cv, const char* text, int x, int y, int size);
void drawIcon(yat::Canvas& cv, const char* name, int x, int y, int size, yat::Ink ink);

}  // namespace prov

void drawProvisioningScreen(const char* reasonZh, const char* reasonEn);
void drawStandardFooter(yat::Canvas& canvas, yat::FontProvider& font);

// Which firmware-owned card the panel is currently holding, persisted in NVS
// ("card_on_screen") because the conditions that draw one outlive a deep sleep
// and so does the card. Two jobs, both about the ~30 s refresh a card costs:
// draw it only on the FIRST wake of a streak, and force a render on the first
// wake after its condition clears, so a card can never outlive the problem it
// describes (hash-skip renders nothing while the data sits still). The offline
// card keeps its own streak counter (trackOfflineCycle) and stays out of this.
enum class ScreenCard : uint8_t {
  None = 0,
  LowBattery = 1,
  SetupRefused = 2,
  Offline = 3,   // drawOfflineCard: the WiFi join failed
  NoData = 4,    // drawNoDataCard: WiFi is up, the pack's sources are not
  // drawHelpCard: the one card with no condition behind it at all — the user
  // asked for it, and the very next wake is meant to take it away again. It is
  // in this enum purely so hash-skip cannot strand it: unchanged data would
  // otherwise leave a help screen up for hours in place of the household's
  // pages.
  Help = 5,
  // The two screens runProvisioningMode draws — the live QR one, and the calm
  // "setup closed" one it leaves behind when nobody completes it. Marked for a
  // third reason on top of the two above: an unattended device that keeps
  // failing to reach WiFi re-enters provisioning every retry, and the marker is
  // how it knows the panel is already holding these instructions and a second
  // identical 30 s refresh would buy nothing.
  Provisioning = 6,
  SetupClosed = 7,
  // drawSafeModeCard: the crash-loop breaker stopped this cycle before the pack
  // was loaded (audit #18). Here for the same first-wake-of-a-streak reason as
  // LowBattery — a device that keeps faulting keeps re-entering safe mode, and
  // a 30 s refresh per entry to redraw an identical card is battery spent on
  // nothing at exactly the wrong moment.
  SafeMode = 8,
};

ScreenCard loadScreenCard();
void saveScreenCard(ScreenCard card);

void drawOfflineCard();
void drawNoDataCard(const char* pageId);
void drawSetupClosedCard();
void drawSafeModeCard();
void drawHelpCard(int batteryPct);
void drawLowBatteryCard(int pct);


bool engineDataAllNull(JsonVariantConst data);
bool trackOfflineCycle(bool offlineThisCycle, bool& recovered);
