#pragma once
// Generated by the main.cpp module split: the code below is a verbatim
// slice of the original single-translation-unit firmware/src/main.cpp.

#include <stdint.h>

#include "yat_common.h"

void buildApCreds();

// KEY0 has two gestures, told apart by one sampling loop at wake:
//
//   Hold (still low 5 s later)   -> re-enter WiFi provisioning (PRD §4.3)
//   Tap  (released before that)  -> tap-to-talk voice capture (PRD §4.4)
//
// Only sampled when KEY0 itself caused this wake (ext1), so it costs nothing
// on a timer wake or a KEY1/KEY2 press. The loop is the v0.3 hold check with
// its early "released" return turned into a Tap verdict rather than a bare
// false — one poll, one meaning per outcome, no second pass over the pin.
//
// A very quick tap can be over before the chip finishes booting; that reads as
// HIGH on the first sample and is still a Tap, which is correct — the ext1
// status word is the proof that KEY0 is what woke us.
enum class Key0Gesture { None, Tap, Hold };

Key0Gesture readKey0GestureAtWake();

void clearProvisionStreak();
[[noreturn]] void runProvisioningMode(const char* reasonZh, const char* reasonEn, bool thenPortal,
                                      bool userInitiated);
